name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ~/.dbt
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Poetry using snok/install-poetry
        uses: snok/install-poetry@v1
        with:
          version: '2.1.1'

      - name: Install dependencies via Poetry
        run: poetry install --no-interaction --no-root

      - name: Generate dbt profiles.yml from template
        run: |
          mkdir -p ~/.dbt
          envsubst < profiles.yml.template > ~/.dbt/profiles.yml
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

      - name: Run dbt debug
        run: poetry run dbt debug

      - name: Install dbt dependencies
        run: poetry run dbt deps

      - name: Build dbt models
        run: poetry run dbt run

      - name: Run dbt tests
        run: poetry run dbt test
